# Generated by Django 3.1.1 on 2020-12-08 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='categorys',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
