# Generated by Django 3.1.1 on 2021-06-16 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0004_auto_20210614_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='linkss',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
    ]
