# Generated by Django 3.1.1 on 2021-07-17 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0005_listing_linkss'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='linkss',
        ),
    ]
