# Generated by Django 3.1.1 on 2021-07-17 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0006_remove_listing_linkss'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='cast',
            field=models.TextField(default=None, max_length=1000),
        ),
    ]
