# Generated by Django 3.1.1 on 2021-07-17 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0011_auto_20210717_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='cast',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.TextField(),
        ),
    ]
