# Generated by Django 3.1.1 on 2021-07-17 08:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0012_auto_20210717_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='cast',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
