# Generated by Django 3.1.1 on 2021-07-17 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0013_auto_20210717_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='categorys',
            field=models.CharField(max_length=64),
        ),
    ]
