# Generated by Django 3.1.1 on 2021-07-17 08:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0017_auto_20210717_1402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='cast',
        ),
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
