# Generated by Django 3.1.1 on 2021-07-19 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0018_auto_20210717_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='categoryss',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
