# Generated by Django 3.1.1 on 2021-07-19 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0019_listing_categoryss'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.TextField(max_length=10),
        ),
    ]
