# Generated by Django 3.1.1 on 2021-07-19 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0021_auto_20210719_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.TextField(blank=True, default=None, max_length=64, null=True),
        ),
    ]
