# Generated by Django 3.1.1 on 2021-07-19 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0024_auto_20210719_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='cast',
            field=models.TextField(default=None),
        ),
    ]
