# Generated by Django 3.1.1 on 2021-07-19 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0025_listing_cast'),
    ]

    operations = [
        migrations.AddField(
            model_name='alllisting',
            name='cast',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='alllisting',
            name='description',
            field=models.TextField(default=None),
        ),
    ]
