# Generated by Django 3.1.1 on 2021-07-19 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0026_auto_20210719_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alllisting',
            name='cast',
        ),
    ]
