# Generated by Django 3.1.1 on 2021-07-26 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0027_remove_alllisting_cast'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='trailer',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
    ]
