# Generated by Django 3.1.1 on 2021-07-29 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0029_auto_20210728_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='img',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='imgg',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='link',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='links',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='trailer',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
