# Generated by Django 3.1.1 on 2021-08-03 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0030_auto_20210729_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='title1',
            field=models.CharField(default=None, max_length=64),
        ),
        migrations.AddField(
            model_name='listing',
            name='title2',
            field=models.CharField(default=None, max_length=500),
        ),
    ]
