# Generated by Django 3.1.1 on 2021-08-03 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0031_auto_20210803_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='title1',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='listing',
            name='title2',
            field=models.TextField(default=None),
        ),
    ]
